FROM nginx:stable-alpine

RUN rm -f /etc/nginx/conf.d/default.conf
COPY gbp-main/nginx.conf /etc/nginx/conf.d/default.conf
COPY gbp-main/dist /usr/share/nginx/html

RUN chown -R nginx:nginx /usr/share/nginx/html /var/cache/nginx /var/log/nginx /var/run /etc/nginx && \
    chmod -R 755 /usr/share/nginx/html /var/cache/nginx /var/log/nginx /var/run /etc/nginx

RUN rm -rf /var/cache/apk/* /tmp/*

HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
