version: "3.8"

services:
  gbp-politico:
    build:
      context: .
      dockerfile: Dockerfile.env
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_API_URL=${VITE_SUPABASE_API_URL}
        - VITE_SUPABASE_AUTH_URL=${VITE_SUPABASE_AUTH_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_SERPRO_CPF_API_KEY=${VITE_SERPRO_CPF_API_KEY}
        - VITE_SERPRO_CPF_API_URL=${VITE_SERPRO_CPF_API_URL}
        - VITE_MINIO_ENDPOINT=${VITE_MINIO_ENDPOINT}
        - VITE_MINIO_ACCESS_KEY=${VITE_MINIO_ACCESS_KEY}
        - VITE_MINIO_SECRET_KEY=${VITE_MINIO_SECRET_KEY}
        - VITE_MINIO_BUCKET=${VITE_MINIO_BUCKET}
        - VITE_ASAAS_API_KEY=${VITE_ASAAS_API_KEY}
        - VITE_ASAAS_ENV=${VITE_ASAAS_ENV}
        - VITE_ASAAS_WEBHOOK_SECRET=${VITE_ASAAS_WEBHOOK_SECRET}
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
    container_name: gbp-politico-app
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gbp-network

  # Opcional: Nginx Proxy para múltiplos ambientes
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: gbp-politico-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gbp-politico
    networks:
      - gbp-network
    profiles:
      - proxy

networks:
  gbp-network:
    driver: bridge

# Volumes para desenvolvimento (opcional)
volumes:
  node_modules:
    driver: local